[package]
name = "qz"
version = "0.1.4"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
zstd = "0.5"
crc32fast = "1.3.2"
lz4-compression = "0.7.0"